sonar.projectKey=MPCoreDeveloper_ServiceMq
sonar.organization=mpcoredeveloper
sonar.host.url=https://sonarcloud.io

sonar.sources=src/ServiceMq,src/ServiceMq.SharpCoreDb,src/ServiceMq.Sqlite
sonar.exclusions=**/obj/**,**/bin/**,**/Migrations/**

sonar.sourceEncoding=utf-8
